### ISSUE TITLE
replace 'like' url with thumb emoji

### ISSUE THREAD

**Issue by fejjj** [bitlbee/bitlbee-facebook#188] opened 2019-09-16 02:39 UTC
replace 'like' url with thumb emoji.
example URLs:
https://scontent.xx.fbcdn.net/v/t39.1997-6/s168x128/851582_369239386556143_1497813874_n.png?_nc_cat=1&_nc_oc=AQn9YOMFt6BkNyqY6d6ry2vc2-JounVOsu9j0s00yb5Up_CA25LK_UErHeszPS7FmofgsIgiuQxIhH0DYUkCK4tV&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=ad1468ec8233285654c9ed3335832bdd&oe=5E03A934

https://scontent.xx.fbcdn.net/v/t39.1997-6/39178562_1505197616293642_5411344281094848512_n.png?_nc_cat=1&_nc_oc=AQkBFCfALWI6pkpCxap3745U9MLTgIWW-Q0s9d2vTYEK2mNzHrUs5QsYsFojzxXkNcUM7VTnnqNfLGcQUbPj8RSW&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=0cfeefe7ede842d27804220f38018222&oe=5DCC3B75

**Comment by dequis** [comment] 2019-09-16 08:11
Duplicate of #72

**Closed by dequis** 2019-09-16 08:11 UTC
