### ISSUE TITLE
group chats seem to top out at 15

### ISSUE THREAD

**Issue by kiwano** [bitlbee/bitlbee-facebook#158] opened 2017-11-08 15:32 UTC
i was getting into a group chat through the website, and it didn't show up when i did
fbchats facebook
since there were 15 chats, and that's a 2^n-1 type number, i left old group chats until i was back down to 14
before anyone said anything in the new chat, i once again did
fbchats facebook
and the existing 14 chats were listed. i then did
account facebook set group_chat_open all
and said something through the web interface to the chat, and the chat got added and the channel opened.
i'm guessing that this means that the chats are stored in an array of length 15 or somesuch; maybe it could be bumped up to 256? (if i have a few minutes -- which i sadly doubt will happen for the next few weeks -- i might peek through the code and see if i can attend to this myself).

**Comment by dgw** [comment] 2017-11-08 15:44
The issue is flooding the BitlBee client if there are more chats returned by `fbchats`. They should be sorted by last message (latest first); #155 tracks that not happening currently (and points to a workaround).

**Comment by dequis** [comment] 2017-11-18 19:02
Duplicate of #155

**Closed by dequis** 2017-11-18 19:02 UTC
